name: worker

on:
  push:

jobs:
  four:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: ["raw", "puzzling", "function", "shortcoming", "collision"]
        replace: ["carpenter", "rug", "sheet", "evident"]
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: '25'
    - run: java -jar ar
